/*

 AZNAR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 4

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define aznarBank 0

/* Super Gameboy palette 0 */
#define aznarSGBPal0c0 6076
#define aznarSGBPal0c1 8935
#define aznarSGBPal0c2 6596
#define aznarSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define aznarSGBPal1c0 6076
#define aznarSGBPal1c1 8935
#define aznarSGBPal1c2 6596
#define aznarSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define aznarSGBPal2c0 6076
#define aznarSGBPal2c1 8935
#define aznarSGBPal2c2 6596
#define aznarSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define aznarSGBPal3c0 6076
#define aznarSGBPal3c1 8935
#define aznarSGBPal3c2 6596
#define aznarSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define aznarCGBPal0c0 6076
#define aznarCGBPal0c1 8935
#define aznarCGBPal0c2 6596
#define aznarCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define aznarCGBPal1c0 32767
#define aznarCGBPal1c1 639
#define aznarCGBPal1c2 14356
#define aznarCGBPal1c3 34

/* Gameboy Color palette 2 */
#define aznarCGBPal2c0 32767
#define aznarCGBPal2c1 639
#define aznarCGBPal2c2 10570
#define aznarCGBPal2c3 34

/* Gameboy Color palette 3 */
#define aznarCGBPal3c0 6076
#define aznarCGBPal3c1 8935
#define aznarCGBPal3c2 6596
#define aznarCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define aznarCGBPal4c0 6076
#define aznarCGBPal4c1 8935
#define aznarCGBPal4c2 6596
#define aznarCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define aznarCGBPal5c0 6076
#define aznarCGBPal5c1 8935
#define aznarCGBPal5c2 6596
#define aznarCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define aznarCGBPal6c0 6076
#define aznarCGBPal6c1 8935
#define aznarCGBPal6c2 6596
#define aznarCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define aznarCGBPal7c0 6076
#define aznarCGBPal7c1 8935
#define aznarCGBPal7c2 6596
#define aznarCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char aznarCGB[];
/* Start of tile array. */
extern unsigned char aznar[];

/* End of AZNAR.H */
