/*

 FLAG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define flagBank 0

/* Super Gameboy palette 0 */
#define flagSGBPal0c0 6076
#define flagSGBPal0c1 8935
#define flagSGBPal0c2 6596
#define flagSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define flagSGBPal1c0 6076
#define flagSGBPal1c1 8935
#define flagSGBPal1c2 6596
#define flagSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define flagSGBPal2c0 6076
#define flagSGBPal2c1 8935
#define flagSGBPal2c2 6596
#define flagSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define flagSGBPal3c0 6076
#define flagSGBPal3c1 8935
#define flagSGBPal3c2 6596
#define flagSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define flagCGBPal0c0 6076
#define flagCGBPal0c1 8935
#define flagCGBPal0c2 6596
#define flagCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define flagCGBPal1c0 32767
#define flagCGBPal1c1 639
#define flagCGBPal1c2 14356
#define flagCGBPal1c3 34

/* Gameboy Color palette 2 */
#define flagCGBPal2c0 32767
#define flagCGBPal2c1 639
#define flagCGBPal2c2 10570
#define flagCGBPal2c3 34

/* Gameboy Color palette 3 */
#define flagCGBPal3c0 32767
#define flagCGBPal3c1 445
#define flagCGBPal3c2 337
#define flagCGBPal3c3 34

/* Gameboy Color palette 4 */
#define flagCGBPal4c0 32767
#define flagCGBPal4c1 14942
#define flagCGBPal4c2 281
#define flagCGBPal4c3 1168

/* Gameboy Color palette 5 */
#define flagCGBPal5c0 32767
#define flagCGBPal5c1 23254
#define flagCGBPal5c2 255
#define flagCGBPal5c3 34

/* Gameboy Color palette 6 */
#define flagCGBPal6c0 32767
#define flagCGBPal6c1 31961
#define flagCGBPal6c2 863
#define flagCGBPal6c3 34

/* Gameboy Color palette 7 */
#define flagCGBPal7c0 6076
#define flagCGBPal7c1 8935
#define flagCGBPal7c2 6596
#define flagCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char flagCGB[];
/* Start of tile array. */
extern unsigned char flag[];

/* End of FLAG.H */
