/*

 PARTICLES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define particlesBank 0

/* Super Gameboy palette 0 */
#define particlesSGBPal0c0 6076
#define particlesSGBPal0c1 8935
#define particlesSGBPal0c2 6596
#define particlesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define particlesSGBPal1c0 6076
#define particlesSGBPal1c1 8935
#define particlesSGBPal1c2 6596
#define particlesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define particlesSGBPal2c0 6076
#define particlesSGBPal2c1 8935
#define particlesSGBPal2c2 6596
#define particlesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define particlesSGBPal3c0 6076
#define particlesSGBPal3c1 8935
#define particlesSGBPal3c2 6596
#define particlesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define particlesCGBPal0c0 6076
#define particlesCGBPal0c1 8935
#define particlesCGBPal0c2 6596
#define particlesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define particlesCGBPal1c0 32767
#define particlesCGBPal1c1 639
#define particlesCGBPal1c2 14356
#define particlesCGBPal1c3 34

/* Gameboy Color palette 2 */
#define particlesCGBPal2c0 32767
#define particlesCGBPal2c1 639
#define particlesCGBPal2c2 10570
#define particlesCGBPal2c3 34

/* Gameboy Color palette 3 */
#define particlesCGBPal3c0 32767
#define particlesCGBPal3c1 445
#define particlesCGBPal3c2 337
#define particlesCGBPal3c3 34

/* Gameboy Color palette 4 */
#define particlesCGBPal4c0 32767
#define particlesCGBPal4c1 14942
#define particlesCGBPal4c2 159
#define particlesCGBPal4c3 118

/* Gameboy Color palette 5 */
#define particlesCGBPal5c0 6076
#define particlesCGBPal5c1 8935
#define particlesCGBPal5c2 6596
#define particlesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define particlesCGBPal6c0 6076
#define particlesCGBPal6c1 8935
#define particlesCGBPal6c2 6596
#define particlesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define particlesCGBPal7c0 6076
#define particlesCGBPal7c1 8935
#define particlesCGBPal7c2 6596
#define particlesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char particlesCGB[];
/* Start of tile array. */
extern unsigned char particles[];

/* End of PARTICLES.H */
