/*

 PRINCESS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define princessBank 0

/* Super Gameboy palette 0 */
#define princessSGBPal0c0 6076
#define princessSGBPal0c1 8935
#define princessSGBPal0c2 6596
#define princessSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define princessSGBPal1c0 6076
#define princessSGBPal1c1 8935
#define princessSGBPal1c2 6596
#define princessSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define princessSGBPal2c0 6076
#define princessSGBPal2c1 8935
#define princessSGBPal2c2 6596
#define princessSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define princessSGBPal3c0 6076
#define princessSGBPal3c1 8935
#define princessSGBPal3c2 6596
#define princessSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define princessCGBPal0c0 6076
#define princessCGBPal0c1 8935
#define princessCGBPal0c2 6596
#define princessCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define princessCGBPal1c0 32767
#define princessCGBPal1c1 572
#define princessCGBPal1c2 14356
#define princessCGBPal1c3 34

/* Gameboy Color palette 2 */
#define princessCGBPal2c0 6076
#define princessCGBPal2c1 8935
#define princessCGBPal2c2 6596
#define princessCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define princessCGBPal3c0 6076
#define princessCGBPal3c1 8935
#define princessCGBPal3c2 6596
#define princessCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define princessCGBPal4c0 6076
#define princessCGBPal4c1 8935
#define princessCGBPal4c2 6596
#define princessCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define princessCGBPal5c0 6076
#define princessCGBPal5c1 8935
#define princessCGBPal5c2 6596
#define princessCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define princessCGBPal6c0 6076
#define princessCGBPal6c1 8935
#define princessCGBPal6c2 6596
#define princessCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define princessCGBPal7c0 6076
#define princessCGBPal7c1 8935
#define princessCGBPal7c2 6596
#define princessCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char princessCGB[];
/* Start of tile array. */
extern unsigned char princess[];

/* End of PRINCESS.H */
