/*

 SPLASHTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 103

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define splashtilesBank 0

/* Super Gameboy palette 0 */
#define splashtilesSGBPal0c0 6076
#define splashtilesSGBPal0c1 8935
#define splashtilesSGBPal0c2 6596
#define splashtilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define splashtilesSGBPal1c0 6076
#define splashtilesSGBPal1c1 8935
#define splashtilesSGBPal1c2 6596
#define splashtilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define splashtilesSGBPal2c0 6076
#define splashtilesSGBPal2c1 8935
#define splashtilesSGBPal2c2 6596
#define splashtilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define splashtilesSGBPal3c0 6076
#define splashtilesSGBPal3c1 8935
#define splashtilesSGBPal3c2 6596
#define splashtilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define splashtilesCGBPal0c0 29566
#define splashtilesCGBPal0c1 8935
#define splashtilesCGBPal0c2 0
#define splashtilesCGBPal0c3 9213

/* Gameboy Color palette 1 */
#define splashtilesCGBPal1c0 29566
#define splashtilesCGBPal1c1 5728
#define splashtilesCGBPal1c2 31262
#define splashtilesCGBPal1c3 10288

/* Gameboy Color palette 2 */
#define splashtilesCGBPal2c0 29566
#define splashtilesCGBPal2c1 856
#define splashtilesCGBPal2c2 564
#define splashtilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define splashtilesCGBPal3c0 6076
#define splashtilesCGBPal3c1 8935
#define splashtilesCGBPal3c2 6596
#define splashtilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define splashtilesCGBPal4c0 6076
#define splashtilesCGBPal4c1 8935
#define splashtilesCGBPal4c2 6596
#define splashtilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define splashtilesCGBPal5c0 6076
#define splashtilesCGBPal5c1 8935
#define splashtilesCGBPal5c2 6596
#define splashtilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define splashtilesCGBPal6c0 6076
#define splashtilesCGBPal6c1 8935
#define splashtilesCGBPal6c2 6596
#define splashtilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define splashtilesCGBPal7c0 6076
#define splashtilesCGBPal7c1 8935
#define splashtilesCGBPal7c2 6596
#define splashtilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char splashtilesCGB[];
/* Start of tile array. */
extern unsigned char splashtiles[];

/* End of SPLASHTILES.H */
