/*

 SRC/ZURRAPA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define zurrapaBank 0

/* Super Gameboy palette 0 */
#define zurrapaSGBPal0c0 6076
#define zurrapaSGBPal0c1 8935
#define zurrapaSGBPal0c2 6596
#define zurrapaSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define zurrapaSGBPal1c0 6076
#define zurrapaSGBPal1c1 8935
#define zurrapaSGBPal1c2 6596
#define zurrapaSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define zurrapaSGBPal2c0 6076
#define zurrapaSGBPal2c1 8935
#define zurrapaSGBPal2c2 6596
#define zurrapaSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define zurrapaSGBPal3c0 6076
#define zurrapaSGBPal3c1 8935
#define zurrapaSGBPal3c2 6596
#define zurrapaSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define zurrapaCGBPal0c0 6076
#define zurrapaCGBPal0c1 8935
#define zurrapaCGBPal0c2 6596
#define zurrapaCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define zurrapaCGBPal1c0 32767
#define zurrapaCGBPal1c1 639
#define zurrapaCGBPal1c2 14356
#define zurrapaCGBPal1c3 34

/* Gameboy Color palette 2 */
#define zurrapaCGBPal2c0 32767
#define zurrapaCGBPal2c1 639
#define zurrapaCGBPal2c2 10570
#define zurrapaCGBPal2c3 34

/* Gameboy Color palette 3 */
#define zurrapaCGBPal3c0 32767
#define zurrapaCGBPal3c1 445
#define zurrapaCGBPal3c2 337
#define zurrapaCGBPal3c3 34

/* Gameboy Color palette 4 */
#define zurrapaCGBPal4c0 6076
#define zurrapaCGBPal4c1 8935
#define zurrapaCGBPal4c2 6596
#define zurrapaCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define zurrapaCGBPal5c0 6076
#define zurrapaCGBPal5c1 8935
#define zurrapaCGBPal5c2 6596
#define zurrapaCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define zurrapaCGBPal6c0 6076
#define zurrapaCGBPal6c1 8935
#define zurrapaCGBPal6c2 6596
#define zurrapaCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define zurrapaCGBPal7c0 6076
#define zurrapaCGBPal7c1 8935
#define zurrapaCGBPal7c2 6596
#define zurrapaCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char zurrapaCGB[];
/* Start of tile array. */
extern unsigned char zurrapa[];

/* End of SRC/ZURRAPA.H */
